version: "2.4"

services:
  iac-terra:
      build:
        context: .
        target: dev
        dockerfile: ./terraform.Dockerfile
      volumes:
        - ./bin/.:/app
      env_file:
        - ./.env/app.env
      stdin_open: true
      tty: true
